class Error(Exception):
    pass

class TargetNotFound(Error):
    pass